// Generates program/src/channels/live/default-ignorables-data.ts from Unicode's DerivedCoreProperties.txt
// (Default_Ignorable_Code_Point ranges). Used by the forbidden-term tests as an authoritative corpus.
// Usage: pnpm exec tsx scripts/generate-default-ignorables.ts <path/to/DerivedCoreProperties.txt>
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const input = process.argv[2];
if (!input) throw new Error("usage: tsx scripts/generate-default-ignorables.ts <DerivedCoreProperties.txt>");
const text = readFileSync(input, "utf8");
const version = /DerivedCoreProperties-(\S+)\.txt/u.exec(text)?.[1] ?? "unknown";
const sha256 = createHash("sha256").update(text).digest("hex");
const ranges: Array<[number, number]> = [];
for (const line of text.split("\n")) {
  const body = line.split("#")[0]?.trim();
  if (!body) continue;
  const [codes, property] = body.split(";").map((part) => part.trim());
  if (property !== "Default_Ignorable_Code_Point" || !codes) continue;
  const [from, to] = codes.split("..").map((hex) => Number.parseInt(hex, 16));
  ranges.push([from!, to ?? from!]);
}
const out = `// GENERATED by scripts/generate-default-ignorables.ts — do not edit by hand.
// Source: Unicode DerivedCoreProperties.txt ${version}, Default_Ignorable_Code_Point, sha256 ${sha256}.
// https://www.unicode.org/Public/${version}/ucd/DerivedCoreProperties.txt — Unicode terms of use apply.
export const DEFAULT_IGNORABLE_RANGES: ReadonlyArray<readonly [number, number]> = Object.freeze([
${ranges.map(([a, b]) => `  [0x${a.toString(16)}, 0x${b.toString(16)}],`).join("\n")}
]);
`;
writeFileSync(path.resolve(import.meta.dirname, "../src/channels/live/default-ignorables-data.ts"), out);
console.log(`wrote ${ranges.length} ranges (Unicode ${version})`);
