// Generates program/src/channels/live/confusables-data.ts from Unicode's UTS #39 confusables.txt.
// Usage: pnpm exec tsx scripts/generate-confusables.ts <path/to/confusables.txt> <path/to/CaseFolding.txt>
//
// Subset criterion (asserted by forbidden-corpus.test.ts through the stored UTS39_SUBSET_SIZE / UTS39_SKELETON_SIZE):
// every confusables.txt mapping with a single-code-point source whose prototype, after mark removal (NFD, then
// \p{M} removed; forbiddenSkeleton strips marks too) and full case folding (CaseFolding.txt C + F), consists only of
// ASCII letters/digits; ASCII sources only when the prototype differs from their folded form (I -> l, 0 -> o, m -> rn).
// Keyed by the source, plus a lowercase alias only where Unicode has no direct entry for the lowercase letter.
import { writeFileSync } from "node:fs";
import path from "node:path";

import { fullCaseFolding, readUcd } from "./lib/ucd.js";

const input = process.argv[2];
const foldingInput = process.argv[3];
if (!input || !foldingInput) throw new Error("usage: tsx scripts/generate-confusables.ts <confusables.txt> <CaseFolding.txt>");
const { text, sha256, version } = readUcd(input, /# Version: (\S+)/u);
const date = /# Date: ([^\n]+)/u.exec(text)?.[1]?.trim() ?? "unknown";
const folding = readUcd(foldingInput, /CaseFolding-(\S+)\.txt/u);
const foldMap = fullCaseFolding(folding.text);
const fold = (value: string) => [...value].map((char) => String.fromCodePoint(...(foldMap.get(char.codePointAt(0)!) ?? [char.codePointAt(0)!]))).join("");

const direct = new Map<string, string>();
for (const line of text.split("\n")) {
  const body = line.split("#")[0]?.trim();
  if (!body) continue;
  const [source, target] = body.split(";").map((part) => part.trim());
  if (!source || !target || source.includes(" ")) continue;
  const from = String.fromCodePoint(Number.parseInt(source, 16));
  const to = target
    .split(" ")
    .map((hex) => String.fromCodePoint(Number.parseInt(hex, 16)))
    .join("")
    .normalize("NFD")
    .replace(/\p{M}/gu, "");
  const folded = fold(to).normalize("NFD").replace(/\p{M}/gu, "");
  if (!/^[a-z0-9]+$/u.test(folded)) continue;
  // ASCII sources are kept only when the prototype differs from their folded form (e.g. I -> l, 0 -> o).
  if (from.codePointAt(0)! < 0x80 && folded === fold(from)) continue;
  if (!direct.has(from)) direct.set(from, folded);
}
// Direct entries first; a lowercase alias only where Unicode has no direct entry for that lowercase letter
// (otherwise a capital's prototype would replace the lowercase letter's own, e.g. Greek capital Eta -> h over eta -> n).
const map = new Map(direct);
for (const [from, to] of direct) {
  const lower = from.toLowerCase();
  if ([...lower].length !== 1 || lower.codePointAt(0)! < 0x80 || map.has(lower)) continue;
  map.set(lower, to);
}

const escape = (value: string) => [...value].map((char) => `\\u{${char.codePointAt(0)!.toString(16)}}`).join("");
const entries = [...map.entries()].sort(([a], [b]) => a.codePointAt(0)! - b.codePointAt(0)!);
const out = `// GENERATED by scripts/generate-confusables.ts — do not edit by hand.
// Source: Unicode UTS #39 confusables.txt, version ${version} (${date}), sha256 ${sha256}.
// https://www.unicode.org/Public/security/${version}/confusables.txt — Unicode terms of use apply.
// Case folding: Unicode CaseFolding.txt ${folding.version} (C + F), sha256 ${folding.sha256}.
// Subset criterion: every confusables.txt mapping with a single-code-point source whose prototype, after mark removal
// and full case folding, consists only of ASCII letters/digits; ASCII sources only when the prototype differs from
// their folded form. UTS39_SUBSET_SIZE counts those mappings; UTS39_SKELETON_SIZE adds the lowercase aliases.
export const UTS39_VERSION = "${version}";
export const UTS39_SUBSET_SIZE = ${direct.size};
export const UTS39_SKELETON_SIZE = ${entries.length};
export const UTS39_SKELETON: Readonly<Record<string, string>> = Object.freeze({
${entries.map(([from, to]) => `  "${escape(from)}": "${to}",`).join("\n")}
});
`;
const target = path.resolve(import.meta.dirname, "../src/channels/live/confusables-data.ts");
writeFileSync(target, out);
console.log(`wrote ${entries.length} entries (${direct.size} direct) (UTS #39 ${version}) to ${target}`);
