// Generates program/src/channels/live/confusables-data.ts from Unicode's UTS #39 confusables.txt.
// Usage: pnpm exec tsx scripts/generate-confusables.ts <path/to/confusables.txt>
// Keeps single-code-point sources (not ASCII) whose prototype is ASCII letters/digits after removing combining
// marks (forbiddenSkeleton strips them too) and lowercasing,
// keyed by the source and by its lowercase form (forbiddenSkeleton lowercases before the lookup).
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const input = process.argv[2];
if (!input) throw new Error("usage: tsx scripts/generate-confusables.ts <confusables.txt>");
const text = readFileSync(input, "utf8");
const version = /# Version: (\S+)/u.exec(text)?.[1] ?? "unknown";
const date = /# Date: ([^\n]+)/u.exec(text)?.[1]?.trim() ?? "unknown";
const sha256 = createHash("sha256").update(text).digest("hex");

const map = new Map<string, string>();
for (const line of text.split("\n")) {
  const body = line.split("#")[0]?.trim();
  if (!body) continue;
  const [source, target] = body.split(";").map((part) => part.trim());
  if (!source || !target || source.includes(" ")) continue;
  const from = String.fromCodePoint(Number.parseInt(source, 16));
  if (from.codePointAt(0)! < 0x80) continue;
  const to = target
    .split(" ")
    .map((hex) => String.fromCodePoint(Number.parseInt(hex, 16)))
    .join("")
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLowerCase();
  if (!/^[a-z0-9]+$/u.test(to)) continue;
  for (const key of new Set([from, from.toLowerCase()])) {
    if (key.codePointAt(0)! < 0x80 || [...key].length !== 1) continue;
    if (!map.has(key)) map.set(key, to);
  }
}

const escape = (value: string) => [...value].map((char) => `\\u{${char.codePointAt(0)!.toString(16)}}`).join("");
const entries = [...map.entries()].sort(([a], [b]) => a.codePointAt(0)! - b.codePointAt(0)!);
const out = `// GENERATED by scripts/generate-confusables.ts — do not edit by hand.
// Source: Unicode UTS #39 confusables.txt, version ${version} (${date}), sha256 ${sha256}.
// https://www.unicode.org/Public/security/${version}/confusables.txt — Unicode terms of use apply.
// Subset: single code point sources (not ASCII) whose prototype is ASCII letters/digits after removing marks and lowercasing.
export const UTS39_SKELETON: Readonly<Record<string, string>> = Object.freeze({
${entries.map(([from, to]) => `  "${escape(from)}": "${to}",`).join("\n")}
});
`;
const target = path.resolve(import.meta.dirname, "../src/channels/live/confusables-data.ts");
writeFileSync(target, out);
console.log(`wrote ${entries.length} entries (UTS #39 ${version}) to ${target}`);
