// Generates, from UnicodeData.txt and CaseFolding.txt (version-exact; the runtime's normalize/toLowerCase/\p{...} are
// not used here, because Node's ICU can be a Unicode version behind):
// - program/src/channels/live/compat-readings-data.ts (RUNTIME): term readings of compatibility decompositions, so the
//   matcher reads e.g. U+209D LATIN SUBSCRIPT SMALL LETTER W as "w" even where the runtime NFKC does not know it.
// - program/src/channels/live/unicode-corpus-data.ts (TESTS ONLY): Mn ranges and the case-folding corpus.
// Usage: pnpm exec tsx scripts/generate-unicode-corpus.ts <path/to/UnicodeData.txt> <path/to/CaseFolding.txt>
//
// Criteria ("term characters" are ASCII letters and digits, compared case-insensitively; "mark removal" removes
// General_Category=Mn code points after canonical decomposition, as the matcher does):
// - MN_RANGES: every General_Category=Mn code point (UnicodeData.txt field 2), as merged inclusive ranges.
// - CASE_FOLD_CORPUS: every code point with a C or F folding (CaseFolding.txt) whose folded result, after mark removal,
//   consists only of term characters (ẞ -> ss, K KELVIN SIGN -> k, Å ANGSTROM SIGN -> a).
//   U+0149 (-> U+02BC n) and U+1E9A (-> a U+02BE) fold to a modifier letter, which is not a term character: excluded.
// - COMPAT_STRICT: every code point with a Decomposition_Mapping whose full compatibility decomposition (NFKD, i.e. its
//   NFKC form) is a string of term characters (ﬃ -> ffi, Ⅻ -> xii, ⑩ -> 10, 𝐀 -> a).
// - COMPAT_MARKED: the remaining code points whose NFKD becomes such a string only after mark removal and full case
//   folding (é -> e, ǅ -> dz).
// Entries are packed "source:target" with the source in hex and the target as lowercase ASCII.
import { writeFileSync } from "node:fs";
import path from "node:path";

import { asTerm, compatTermReadings, fullCaseFolding, packedLiteral, parseUnicodeData, readUcd, stripMarks } from "./lib/ucd.js";

const [dataInput, foldingInput] = process.argv.slice(2);
if (!dataInput || !foldingInput) throw new Error("usage: tsx scripts/generate-unicode-corpus.ts <UnicodeData.txt> <CaseFolding.txt>");
const ucd = readUcd(dataInput, /$^/u);
const folding = readUcd(foldingInput, /CaseFolding-(\S+)\.txt/u);
const version = folding.version;
const data = parseUnicodeData(ucd.text);
const foldMap = fullCaseFolding(folding.text);
const hex = (code: number) => code.toString(16);
const pack = (entries: Array<[number, string]>) => packedLiteral(entries.map(([code, term]) => `${hex(code)}:${term}`));
const source = `// Source: Unicode UnicodeData.txt ${version}, sha256 ${ucd.sha256};
// CaseFolding.txt ${version} (C + F), sha256 ${folding.sha256}.
// https://www.unicode.org/Public/${version}/ucd/ — Unicode terms of use apply. Criteria: see the generator header.`;

const caseFold: Array<[number, string]> = [];
for (const [code, mapping] of [...foldMap.entries()].sort(([a], [b]) => a - b)) {
  const term = asTerm(stripMarks(data, mapping));
  if (term) caseFold.push([code, term]);
}
const { strict, marked } = compatTermReadings(data, foldMap);
const mnSize = data.mnRanges.reduce((sum, [a, b]) => sum + b - a + 1, 0);

const corpus = `// GENERATED by scripts/generate-unicode-corpus.ts — do not edit by hand. Test corpora only (not used at runtime).
${source}
export const UNICODE_CORPUS_VERSION = "${version}";

/** General_Category=Mn, merged inclusive ranges. */
export const MN_SIZE = ${mnSize};
export const MN_RANGES: ReadonlyArray<readonly [number, number]> = Object.freeze([
${packedLiteral(data.mnRanges.map(([a, b]) => `[0x${hex(a)}, 0x${hex(b)}]`)).replace(/"/gu, "").replace(/ \+$/gmu, "").replace(/\],\[/gu, "], [")}
]);

/** Code points with a C/F folding whose folded result, after mark removal, is term characters. */
export const CASE_FOLD_CORPUS_SIZE = ${caseFold.length};
export const CASE_FOLD_CORPUS =
${pack(caseFold)};
`;
const runtime = `// GENERATED by scripts/generate-unicode-corpus.ts — do not edit by hand.
${source}
// Term readings of compatibility decompositions, version-exact (the runtime's NFKC may be a Unicode version behind).
export const COMPAT_READINGS_VERSION = "${version}";
/** NFKD is a string of ASCII letters/digits (lowercased here). */
export const COMPAT_STRICT_SIZE = ${strict.length};
export const COMPAT_STRICT =
${pack(strict)};
/** NFKD reads as ASCII letters/digits only after mark removal and full case folding. */
export const COMPAT_MARKED_SIZE = ${marked.length};
export const COMPAT_MARKED =
${pack(marked)};
`;
const dir = path.resolve(import.meta.dirname, "../src/channels/live");
writeFileSync(path.join(dir, "unicode-corpus-data.ts"), corpus);
writeFileSync(path.join(dir, "compat-readings-data.ts"), runtime);
console.log(`wrote Mn ${mnSize} code points (${data.mnRanges.length} ranges), case fold ${caseFold.length}, compat ${strict.length} + ${marked.length} marked (Unicode ${version})`);
