// Generates program/src/channels/live/case-folding-data.ts from Unicode's CaseFolding.txt.
// Usage: pnpm exec tsx scripts/generate-case-folding.ts <path/to/CaseFolding.txt>
// Keeps statuses C (common) and F (full, multi-character folds such as U+1E9E -> "ss", U+0149 -> U+02BC "n"): together
// they are the full case folding. S (simple) is the single-character alternative to an F entry and is not part of the
// full folding; T (Turkic I/dotless i) is locale-specific and only replaces the C entries for U+0049/U+0130, whose
// C/F folds (i, i + combining dot) already read as "i" after mark removal. Neither is needed for full-fold correctness.
import { writeFileSync } from "node:fs";
import path from "node:path";

import { fullCaseFolding, packedLiteral, readUcd } from "./lib/ucd.js";

const input = process.argv[2];
if (!input) throw new Error("usage: tsx scripts/generate-case-folding.ts <CaseFolding.txt>");
const { text, sha256, version } = readUcd(input, /CaseFolding-(\S+)\.txt/u);
const folding = [...fullCaseFolding(text).entries()].sort(([a], [b]) => a - b);
const hex = (code: number) => code.toString(16);
// Compact form: "source:target target,..." in hex; parsed once at module load.
const packed = packedLiteral(folding.map(([from, to]) => `${hex(from)}:${to.map(hex).join(" ")}`));
const out = `// GENERATED by scripts/generate-case-folding.ts — do not edit by hand.
// Source: Unicode CaseFolding.txt ${version}, statuses C and F (full case folding), sha256 ${sha256}.
// https://www.unicode.org/Public/${version}/ucd/CaseFolding.txt — Unicode terms of use apply.
// S and T are left out: S is the simple alternative to an F entry; T (Turkic) only changes I/İ, which read "i" anyway.
export const CASE_FOLDING_VERSION = "${version}";
export const CASE_FOLDING_SIZE = ${folding.length};
export const CASE_FOLDING_PACKED =
${packed};
`;
const target = path.resolve(import.meta.dirname, "../src/channels/live/case-folding-data.ts");
writeFileSync(target, out);
console.log(`wrote ${folding.length} C/F foldings (Unicode ${version}) to ${target}`);
