import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import * as Dialog from "@radix-ui/react-dialog";
import * as Tabs from "@radix-ui/react-tabs";
import { AlertTriangle, Check, Code2, Copy, LoaderCircle, LogOut, Plug, ShieldCheck, TerminalSquare, X } from "lucide-react";
import { Button, IconButton, Tag } from "@doppelganger/ui";

import { getAgentCapabilities, getOpenApi, getProviderSettings, logoutOperator, saveProviderSettings } from "./api";
import type { FrontendBootstrap, OperatorSession, ProviderSettings } from "./types";
import { errorCopy, StatePanel, words } from "./ui";

function ProviderSettingsPanel() {
  const settings = useQuery({ queryKey: ["provider-settings"], queryFn: getProviderSettings, retry: false });
  const [draft, setDraft] = useState<ProviderSettings["values"] & { composioApiKey: string }>({ composioBaseUrl: "", composioDefaultUserId: "", composioDefaultConnectedAccountId: "", composioApiKey: "" });
  useEffect(() => { if (settings.data) setDraft({ ...settings.data.values, composioApiKey: "" }); }, [settings.data]);
  const mutation = useMutation({ mutationFn: () => saveProviderSettings({ ...draft, ...(draft.composioApiKey ? { composioApiKey: draft.composioApiKey } : {}) }), onSuccess: async () => { setDraft((value) => ({ ...value, composioApiKey: "" })); await settings.refetch(); } });
  if (settings.isLoading) return <p className="muted">Loading redacted provider settings…</p>;
  if (settings.error) return <StatePanel error={settings.error} onRetry={() => void settings.refetch()} />;
  return <form className="settings-stack" onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}><div className="settings-intro"><div><h3>Composio provider</h3><p>Marketplace owns this provider credential. The browser can replace it but never reads it back.</p></div><Tag tone={settings.data!.status.composioApiKey.configured ? "success" : "warning"}>{settings.data!.status.composioApiKey.configured ? `Configured · …${settings.data!.status.composioApiKey.keyTail}` : "Not configured"}</Tag></div><div className="form-grid two"><label>API base URL<input type="url" value={draft.composioBaseUrl} onChange={(event) => setDraft((value) => ({ ...value, composioBaseUrl: event.target.value }))} required /></label><label>Default user ID<input value={draft.composioDefaultUserId} onChange={(event) => setDraft((value) => ({ ...value, composioDefaultUserId: event.target.value }))} required /></label></div><label>Connected account override<input value={draft.composioDefaultConnectedAccountId} onChange={(event) => setDraft((value) => ({ ...value, composioDefaultConnectedAccountId: event.target.value }))} placeholder="Optional" /></label><label>Replace API key<input type="password" autoComplete="off" value={draft.composioApiKey} onChange={(event) => setDraft((value) => ({ ...value, composioApiKey: event.target.value }))} placeholder="Leave blank to keep the current key" /></label><div className="credential-proof"><ShieldCheck size={18} /><div><strong>Secret remains server-side</strong><p>Source: {settings.data!.status.composioApiKey.source ?? "none"} · fingerprint {settings.data!.status.composioApiKey.fingerprint ?? "—"}</p></div></div>{mutation.error && <p className="inline-error"><AlertTriangle size={14} />{errorCopy(mutation.error).detail}</p>}<div><Button tone="primary" type="submit" disabled={mutation.isPending}>{mutation.isPending ? <LoaderCircle className="spin" size={15} /> : <Check size={15} />}Save provider settings</Button></div></form>;
}

function DeveloperPanel() {
  const contract = useQuery({ queryKey: ["openapi"], queryFn: getOpenApi, retry: false });
  const [raw, setRaw] = useState(false);
  const operations = useMemo(() => {
    const paths = (contract.data?.paths ?? {}) as Record<string, Record<string, { summary?: string; tags?: string[] }>>;
    return Object.entries(paths).flatMap(([route, methods]) => Object.entries(methods).filter(([method]) => ["get", "post", "put", "patch", "delete"].includes(method)).map(([method, operation]) => ({ route, method, ...operation })));
  }, [contract.data]);
  if (contract.isLoading) return <p className="muted">Loading OpenAPI contract…</p>;
  if (contract.error) return <StatePanel error={contract.error} onRetry={() => void contract.refetch()} />;
  return <div className="settings-stack"><div className="settings-intro"><div><h3>Developer contract</h3><p>Machine-readable browser, Hub service, Agent, and cross-app operations with their real authorization posture.</p></div><div className="dialog-actions"><Button size="small" onClick={() => setRaw((value) => !value)}><Code2 size={14} />{raw ? "Operations" : "Raw JSON"}</Button><Button size="small" onClick={() => navigator.clipboard.writeText(JSON.stringify(contract.data, null, 2))}><Copy size={14} />Copy</Button><a className="dg-button dg-button--small" href="/openapi.json" download>Download</a></div></div>{raw ? <pre className="code-view">{JSON.stringify(contract.data, null, 2)}</pre> : <div className="operations-list">{operations.map((operation) => <div key={`${operation.method}-${operation.route}`}><code className={`method method--${operation.method}`}>{operation.method}</code><code>{operation.route}</code><span>{operation.summary}</span></div>)}</div>}</div>;
}

function SecurityPanel({ session, onLogout }: { session: OperatorSession; onLogout: () => void }) {
  const logout = useMutation({ mutationFn: logoutOperator, onSuccess: onLogout });
  return <div className="settings-stack"><div className="settings-intro"><div><h3>Operator session</h3><p>This browser session is distinct from the internal bearer used by Agents, Hub, and cross-app calls.</p></div><ShieldCheck /></div><dl className="contract-list"><dt>Operator</dt><dd>{session.principal?.id ?? "—"}</dd><dt>Organization</dt><dd>{session.principal?.organizationId ?? "—"}</dd><dt>Expires</dt><dd>{session.expiresAt ? new Date(session.expiresAt).toLocaleString() : session.mode === "test_bypass" ? "Test bypass" : "—"}</dd><dt>Browser credential</dt><dd>Opaque HttpOnly cookie; access token is not retained</dd><dt>Mutation proof</dt><dd>Exact Origin plus per-session CSRF token</dd></dl>{logout.error && <p className="inline-error"><AlertTriangle size={14} />{errorCopy(logout.error).detail}</p>}<div><Button tone="danger" disabled={logout.isPending} onClick={() => logout.mutate()}><LogOut size={15} />End operator session</Button></div></div>;
}

export function SettingsDialog({ open, onOpenChange, bootstrap, workspaceSlug, session, onLogout }: { open: boolean; onOpenChange: (open: boolean) => void; bootstrap: FrontendBootstrap; workspaceSlug: string; session: OperatorSession; onLogout: () => void }) {
  const capabilities = useQuery({ queryKey: ["agent-capabilities", workspaceSlug], queryFn: () => getAgentCapabilities(workspaceSlug), enabled: open, retry: false });
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="settings-dialog"><header className="modal-header"><div><p className="eyebrow">Marketplace control plane</p><Dialog.Title>Settings</Dialog.Title><Dialog.Description>Provider configuration, authorization boundaries, Agent projection, and the complete Program contract.</Dialog.Description></div><Dialog.Close asChild><IconButton aria-label="Close settings"><X size={17} /></IconButton></Dialog.Close></header><Tabs.Root className="settings-tabs" defaultValue="providers"><Tabs.List aria-label="Marketplace settings"><Tabs.Trigger value="providers"><Plug size={15} />Providers</Tabs.Trigger><Tabs.Trigger value="security"><ShieldCheck size={15} />Security</Tabs.Trigger><Tabs.Trigger value="authorization"><ShieldCheck size={15} />Authorization</Tabs.Trigger><Tabs.Trigger value="agent"><TerminalSquare size={15} />Agent tools</Tabs.Trigger><Tabs.Trigger value="developer"><Code2 size={15} />Developer</Tabs.Trigger></Tabs.List><div className="settings-content"><Tabs.Content value="providers"><ProviderSettingsPanel /></Tabs.Content><Tabs.Content value="security"><SecurityPanel session={session} onLogout={onLogout} /></Tabs.Content><Tabs.Content value="authorization"><div className="settings-stack"><div className="settings-intro"><div><h3>Authority boundaries</h3><p>Marketplace does not create a second provider or lifecycle control plane.</p></div><ShieldCheck /></div><dl className="contract-list"><dt>Browser operator routes</dt><dd>{bootstrap.authorization.browserOperatorRoutes}</dd><dt>Hub service</dt><dd>Internal bearer required</dd><dt>Cross-app broker v1</dt><dd>Internal bearer required</dd><dt>Credential in browser</dt><dd>No</dd><dt>Mutation authority</dt><dd>Rules Approvals, fail closed</dd></dl>{Object.entries(bootstrap.contractGaps).map(([name, state]) => <div className="contract-gap" key={name}><AlertTriangle size={17} /><div><strong>{words(name)}</strong><p>{words(state)}</p></div></div>)}</div></Tabs.Content><Tabs.Content value="agent"><div className="settings-stack"><div className="settings-intro"><div><h3>Agent projection</h3><p>Only registered, installed, connected, capability-bound, and action-enabled tools appear here.</p></div><Tag tone="accent">{capabilities.data?.capabilities.length ?? 0} tools</Tag></div>{capabilities.error ? <StatePanel error={capabilities.error} onRetry={() => void capabilities.refetch()} /> : <pre className="code-view">{capabilities.isLoading ? "Loading Agent projection…" : JSON.stringify(capabilities.data, null, 2)}</pre>}</div></Tabs.Content><Tabs.Content value="developer"><DeveloperPanel /></Tabs.Content></div></Tabs.Root></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
