// GENERATED by scripts/generate-unicode-corpus.ts — do not edit by hand.
// Source: Unicode UnicodeData.txt 18.0.0, sha256 0736451de439ae7baf1425136617da495e09ee5afbe6e394374db7009ea08950;
// CaseFolding.txt 18.0.0 (C + F), sha256 a004797658a457bec4dc11683e39f69249ea3b595b752dbea6721c4c9f587b0d.
// https://www.unicode.org/Public/18.0.0/ucd/ — Unicode terms of use apply. Criteria: see the generator header.
// Term readings of compatibility decompositions, version-exact (the runtime's NFKC may be a Unicode version behind).
export const COMPAT_READINGS_VERSION = "18.0.0";
/** NFKD is a string of ASCII letters/digits (lowercased here). */
export const COMPAT_STRICT_SIZE = 1225;
export const COMPAT_STRICT =
  "aa:a,b2:2,b3:3,b9:1,ba:o,132:ij,133:ij,17f:s,1c7:lj,1c8:lj,1c9:lj,1ca:nj,1cb:nj,1cc:nj,1f1:dz,1f2:dz,1f3:dz," +
  "2b0:h,2b2:j,2b3:r,2b7:w,2b8:y,2e1:l,2e2:s,2e3:x,1d2c:a,1d2e:b,1d30:d,1d31:e,1d33:g,1d34:h,1d35:i,1d36:j,1d37:k," +
  "1d38:l,1d39:m,1d3a:n,1d3c:o,1d3e:p,1d3f:r,1d40:t,1d41:u,1d42:w,1d43:a,1d47:b,1d48:d,1d49:e,1d4d:g,1d4f:k," +
  "1d50:m,1d52:o,1d56:p,1d57:t,1d58:u,1d5b:v,1d62:i,1d63:r,1d64:u,1d65:v,1d9c:c,1da0:f,1dbb:z,2070:0,2071:i," +
  "2074:4,2075:5,2076:6,2077:7,2078:8,2079:9,207f:n,2080:0,2081:1,2082:2,2083:3,2084:4,2085:5,2086:6,2087:7," +
  "2088:8,2089:9,2090:a,2091:e,2092:o,2093:x,2095:h,2096:k,2097:l,2098:m,2099:n,209a:p,209b:s,209c:t,209d:w," +
  "209e:y,209f:z,20a8:rs,2102:c,210a:g,210b:h,210c:h,210d:h,210e:h,2110:i,2111:i,2112:l,2113:l,2115:n,2116:no," +
  "2119:p,211a:q,211b:r,211c:r,211d:r,2120:sm,2121:tel,2122:tm,2124:z,2128:z,212a:k,212c:b,212d:c,212f:e,2130:e," +
  "2131:f,2133:m,2134:o,2139:i,213b:fax,2145:d,2146:d,2147:e,2148:i,2149:j,2160:i,2161:ii,2162:iii,2163:iv,2164:v," +
  "2165:vi,2166:vii,2167:viii,2168:ix,2169:x,216a:xi,216b:xii,216c:l,216d:c,216e:d,216f:m,2170:i,2171:ii,2172:iii," +
  "2173:iv,2174:v,2175:vi,2176:vii,2177:viii,2178:ix,2179:x,217a:xi,217b:xii,217c:l,217d:c,217e:d,217f:m,2460:1," +
  "2461:2,2462:3,2463:4,2464:5,2465:6,2466:7,2467:8,2468:9,2469:10,246a:11,246b:12,246c:13,246d:14,246e:15," +
  "246f:16,2470:17,2471:18,2472:19,2473:20,24b6:a,24b7:b,24b8:c,24b9:d,24ba:e,24bb:f,24bc:g,24bd:h,24be:i,24bf:j," +
  "24c0:k,24c1:l,24c2:m,24c3:n,24c4:o,24c5:p,24c6:q,24c7:r,24c8:s,24c9:t,24ca:u,24cb:v,24cc:w,24cd:x,24ce:y," +
  "24cf:z,24d0:a,24d1:b,24d2:c,24d3:d,24d4:e,24d5:f,24d6:g,24d7:h,24d8:i,24d9:j,24da:k,24db:l,24dc:m,24dd:n," +
  "24de:o,24df:p,24e0:q,24e1:r,24e2:s,24e3:t,24e4:u,24e5:v,24e6:w,24e7:x,24e8:y,24e9:z,24ea:0,2c7c:j,2c7d:v," +
  "3250:pte,3251:21,3252:22,3253:23,3254:24,3255:25,3256:26,3257:27,3258:28,3259:29,325a:30,325b:31,325c:32," +
  "325d:33,325e:34,325f:35,32b1:36,32b2:37,32b3:38,32b4:39,32b5:40,32b6:41,32b7:42,32b8:43,32b9:44,32ba:45," +
  "32bb:46,32bc:47,32bd:48,32be:49,32bf:50,32cc:hg,32cd:erg,32ce:ev,32cf:ltd,3371:hpa,3372:da,3373:au,3374:bar," +
  "3375:ov,3376:pc,3377:dm,3378:dm2,3379:dm3,337a:iu,3380:pa,3381:na,3383:ma,3384:ka,3385:kb,3386:mb,3387:gb," +
  "3388:cal,3389:kcal,338a:pf,338b:nf,338e:mg,338f:kg,3390:hz,3391:khz,3392:mhz,3393:ghz,3394:thz,3396:ml,3397:dl," +
  "3398:kl,3399:fm,339a:nm,339c:mm,339d:cm,339e:km,339f:mm2,33a0:cm2,33a1:m2,33a2:km2,33a3:mm3,33a4:cm3,33a5:m3," +
  "33a6:km3,33a9:pa,33aa:kpa,33ab:mpa,33ac:gpa,33ad:rad,33b0:ps,33b1:ns,33b3:ms,33b4:pv,33b5:nv,33b7:mv,33b8:kv," +
  "33b9:mv,33ba:pw,33bb:nw,33bd:mw,33be:kw,33bf:mw,33c3:bq,33c4:cc,33c5:cd,33c8:db,33c9:gy,33ca:ha,33cb:hp," +
  "33cc:in,33cd:kk,33ce:km,33cf:kt,33d0:lm,33d1:ln,33d2:log,33d3:lx,33d4:mb,33d5:mil,33d6:mol,33d7:ph,33d9:ppm," +
  "33da:pr,33db:sr,33dc:sv,33dd:wb,33ff:gal,a7f1:s,a7f2:c,a7f3:f,a7f4:q,fb00:ff,fb01:fi,fb02:fl,fb03:ffi,fb04:ffl," +
  "fb05:st,fb06:st,ff10:0,ff11:1,ff12:2,ff13:3,ff14:4,ff15:5,ff16:6,ff17:7,ff18:8,ff19:9,ff21:a,ff22:b,ff23:c," +
  "ff24:d,ff25:e,ff26:f,ff27:g,ff28:h,ff29:i,ff2a:j,ff2b:k,ff2c:l,ff2d:m,ff2e:n,ff2f:o,ff30:p,ff31:q,ff32:r," +
  "ff33:s,ff34:t,ff35:u,ff36:v,ff37:w,ff38:x,ff39:y,ff3a:z,ff41:a,ff42:b,ff43:c,ff44:d,ff45:e,ff46:f,ff47:g," +
  "ff48:h,ff49:i,ff4a:j,ff4b:k,ff4c:l,ff4d:m,ff4e:n,ff4f:o,ff50:p,ff51:q,ff52:r,ff53:s,ff54:t,ff55:u,ff56:v," +
  "ff57:w,ff58:x,ff59:y,ff5a:z,107a5:q,1ccd6:a,1ccd7:b,1ccd8:c,1ccd9:d,1ccda:e,1ccdb:f,1ccdc:g,1ccdd:h,1ccde:i," +
  "1ccdf:j,1cce0:k,1cce1:l,1cce2:m,1cce3:n,1cce4:o,1cce5:p,1cce6:q,1cce7:r,1cce8:s,1cce9:t,1ccea:u,1cceb:v," +
  "1ccec:w,1cced:x,1ccee:y,1ccef:z,1ccf0:0,1ccf1:1,1ccf2:2,1ccf3:3,1ccf4:4,1ccf5:5,1ccf6:6,1ccf7:7,1ccf8:8," +
  "1ccf9:9,1d400:a,1d401:b,1d402:c,1d403:d,1d404:e,1d405:f,1d406:g,1d407:h,1d408:i,1d409:j,1d40a:k,1d40b:l," +
  "1d40c:m,1d40d:n,1d40e:o,1d40f:p,1d410:q,1d411:r,1d412:s,1d413:t,1d414:u,1d415:v,1d416:w,1d417:x,1d418:y," +
  "1d419:z,1d41a:a,1d41b:b,1d41c:c,1d41d:d,1d41e:e,1d41f:f,1d420:g,1d421:h,1d422:i,1d423:j,1d424:k,1d425:l," +
  "1d426:m,1d427:n,1d428:o,1d429:p,1d42a:q,1d42b:r,1d42c:s,1d42d:t,1d42e:u,1d42f:v,1d430:w,1d431:x,1d432:y," +
  "1d433:z,1d434:a,1d435:b,1d436:c,1d437:d,1d438:e,1d439:f,1d43a:g,1d43b:h,1d43c:i,1d43d:j,1d43e:k,1d43f:l," +
  "1d440:m,1d441:n,1d442:o,1d443:p,1d444:q,1d445:r,1d446:s,1d447:t,1d448:u,1d449:v,1d44a:w,1d44b:x,1d44c:y," +
  "1d44d:z,1d44e:a,1d44f:b,1d450:c,1d451:d,1d452:e,1d453:f,1d454:g,1d456:i,1d457:j,1d458:k,1d459:l,1d45a:m," +
  "1d45b:n,1d45c:o,1d45d:p,1d45e:q,1d45f:r,1d460:s,1d461:t,1d462:u,1d463:v,1d464:w,1d465:x,1d466:y,1d467:z," +
  "1d468:a,1d469:b,1d46a:c,1d46b:d,1d46c:e,1d46d:f,1d46e:g,1d46f:h,1d470:i,1d471:j,1d472:k,1d473:l,1d474:m," +
  "1d475:n,1d476:o,1d477:p,1d478:q,1d479:r,1d47a:s,1d47b:t,1d47c:u,1d47d:v,1d47e:w,1d47f:x,1d480:y,1d481:z," +
  "1d482:a,1d483:b,1d484:c,1d485:d,1d486:e,1d487:f,1d488:g,1d489:h,1d48a:i,1d48b:j,1d48c:k,1d48d:l,1d48e:m," +
  "1d48f:n,1d490:o,1d491:p,1d492:q,1d493:r,1d494:s,1d495:t,1d496:u,1d497:v,1d498:w,1d499:x,1d49a:y,1d49b:z," +
  "1d49c:a,1d49e:c,1d49f:d,1d4a2:g,1d4a5:j,1d4a6:k,1d4a9:n,1d4aa:o,1d4ab:p,1d4ac:q,1d4ae:s,1d4af:t,1d4b0:u," +
  "1d4b1:v,1d4b2:w,1d4b3:x,1d4b4:y,1d4b5:z,1d4b6:a,1d4b7:b,1d4b8:c,1d4b9:d,1d4bb:f,1d4bd:h,1d4be:i,1d4bf:j," +
  "1d4c0:k,1d4c1:l,1d4c2:m,1d4c3:n,1d4c5:p,1d4c6:q,1d4c7:r,1d4c8:s,1d4c9:t,1d4ca:u,1d4cb:v,1d4cc:w,1d4cd:x," +
  "1d4ce:y,1d4cf:z,1d4d0:a,1d4d1:b,1d4d2:c,1d4d3:d,1d4d4:e,1d4d5:f,1d4d6:g,1d4d7:h,1d4d8:i,1d4d9:j,1d4da:k," +
  "1d4db:l,1d4dc:m,1d4dd:n,1d4de:o,1d4df:p,1d4e0:q,1d4e1:r,1d4e2:s,1d4e3:t,1d4e4:u,1d4e5:v,1d4e6:w,1d4e7:x," +
  "1d4e8:y,1d4e9:z,1d4ea:a,1d4eb:b,1d4ec:c,1d4ed:d,1d4ee:e,1d4ef:f,1d4f0:g,1d4f1:h,1d4f2:i,1d4f3:j,1d4f4:k," +
  "1d4f5:l,1d4f6:m,1d4f7:n,1d4f8:o,1d4f9:p,1d4fa:q,1d4fb:r,1d4fc:s,1d4fd:t,1d4fe:u,1d4ff:v,1d500:w,1d501:x," +
  "1d502:y,1d503:z,1d504:a,1d505:b,1d507:d,1d508:e,1d509:f,1d50a:g,1d50d:j,1d50e:k,1d50f:l,1d510:m,1d511:n," +
  "1d512:o,1d513:p,1d514:q,1d516:s,1d517:t,1d518:u,1d519:v,1d51a:w,1d51b:x,1d51c:y,1d51e:a,1d51f:b,1d520:c," +
  "1d521:d,1d522:e,1d523:f,1d524:g,1d525:h,1d526:i,1d527:j,1d528:k,1d529:l,1d52a:m,1d52b:n,1d52c:o,1d52d:p," +
  "1d52e:q,1d52f:r,1d530:s,1d531:t,1d532:u,1d533:v,1d534:w,1d535:x,1d536:y,1d537:z,1d538:a,1d539:b,1d53b:d," +
  "1d53c:e,1d53d:f,1d53e:g,1d540:i,1d541:j,1d542:k,1d543:l,1d544:m,1d546:o,1d54a:s,1d54b:t,1d54c:u,1d54d:v," +
  "1d54e:w,1d54f:x,1d550:y,1d552:a,1d553:b,1d554:c,1d555:d,1d556:e,1d557:f,1d558:g,1d559:h,1d55a:i,1d55b:j," +
  "1d55c:k,1d55d:l,1d55e:m,1d55f:n,1d560:o,1d561:p,1d562:q,1d563:r,1d564:s,1d565:t,1d566:u,1d567:v,1d568:w," +
  "1d569:x,1d56a:y,1d56b:z,1d56c:a,1d56d:b,1d56e:c,1d56f:d,1d570:e,1d571:f,1d572:g,1d573:h,1d574:i,1d575:j," +
  "1d576:k,1d577:l,1d578:m,1d579:n,1d57a:o,1d57b:p,1d57c:q,1d57d:r,1d57e:s,1d57f:t,1d580:u,1d581:v,1d582:w," +
  "1d583:x,1d584:y,1d585:z,1d586:a,1d587:b,1d588:c,1d589:d,1d58a:e,1d58b:f,1d58c:g,1d58d:h,1d58e:i,1d58f:j," +
  "1d590:k,1d591:l,1d592:m,1d593:n,1d594:o,1d595:p,1d596:q,1d597:r,1d598:s,1d599:t,1d59a:u,1d59b:v,1d59c:w," +
  "1d59d:x,1d59e:y,1d59f:z,1d5a0:a,1d5a1:b,1d5a2:c,1d5a3:d,1d5a4:e,1d5a5:f,1d5a6:g,1d5a7:h,1d5a8:i,1d5a9:j," +
  "1d5aa:k,1d5ab:l,1d5ac:m,1d5ad:n,1d5ae:o,1d5af:p,1d5b0:q,1d5b1:r,1d5b2:s,1d5b3:t,1d5b4:u,1d5b5:v,1d5b6:w," +
  "1d5b7:x,1d5b8:y,1d5b9:z,1d5ba:a,1d5bb:b,1d5bc:c,1d5bd:d,1d5be:e,1d5bf:f,1d5c0:g,1d5c1:h,1d5c2:i,1d5c3:j," +
  "1d5c4:k,1d5c5:l,1d5c6:m,1d5c7:n,1d5c8:o,1d5c9:p,1d5ca:q,1d5cb:r,1d5cc:s,1d5cd:t,1d5ce:u,1d5cf:v,1d5d0:w," +
  "1d5d1:x,1d5d2:y,1d5d3:z,1d5d4:a,1d5d5:b,1d5d6:c,1d5d7:d,1d5d8:e,1d5d9:f,1d5da:g,1d5db:h,1d5dc:i,1d5dd:j," +
  "1d5de:k,1d5df:l,1d5e0:m,1d5e1:n,1d5e2:o,1d5e3:p,1d5e4:q,1d5e5:r,1d5e6:s,1d5e7:t,1d5e8:u,1d5e9:v,1d5ea:w," +
  "1d5eb:x,1d5ec:y,1d5ed:z,1d5ee:a,1d5ef:b,1d5f0:c,1d5f1:d,1d5f2:e,1d5f3:f,1d5f4:g,1d5f5:h,1d5f6:i,1d5f7:j," +
  "1d5f8:k,1d5f9:l,1d5fa:m,1d5fb:n,1d5fc:o,1d5fd:p,1d5fe:q,1d5ff:r,1d600:s,1d601:t,1d602:u,1d603:v,1d604:w," +
  "1d605:x,1d606:y,1d607:z,1d608:a,1d609:b,1d60a:c,1d60b:d,1d60c:e,1d60d:f,1d60e:g,1d60f:h,1d610:i,1d611:j," +
  "1d612:k,1d613:l,1d614:m,1d615:n,1d616:o,1d617:p,1d618:q,1d619:r,1d61a:s,1d61b:t,1d61c:u,1d61d:v,1d61e:w," +
  "1d61f:x,1d620:y,1d621:z,1d622:a,1d623:b,1d624:c,1d625:d,1d626:e,1d627:f,1d628:g,1d629:h,1d62a:i,1d62b:j," +
  "1d62c:k,1d62d:l,1d62e:m,1d62f:n,1d630:o,1d631:p,1d632:q,1d633:r,1d634:s,1d635:t,1d636:u,1d637:v,1d638:w," +
  "1d639:x,1d63a:y,1d63b:z,1d63c:a,1d63d:b,1d63e:c,1d63f:d,1d640:e,1d641:f,1d642:g,1d643:h,1d644:i,1d645:j," +
  "1d646:k,1d647:l,1d648:m,1d649:n,1d64a:o,1d64b:p,1d64c:q,1d64d:r,1d64e:s,1d64f:t,1d650:u,1d651:v,1d652:w," +
  "1d653:x,1d654:y,1d655:z,1d656:a,1d657:b,1d658:c,1d659:d,1d65a:e,1d65b:f,1d65c:g,1d65d:h,1d65e:i,1d65f:j," +
  "1d660:k,1d661:l,1d662:m,1d663:n,1d664:o,1d665:p,1d666:q,1d667:r,1d668:s,1d669:t,1d66a:u,1d66b:v,1d66c:w," +
  "1d66d:x,1d66e:y,1d66f:z,1d670:a,1d671:b,1d672:c,1d673:d,1d674:e,1d675:f,1d676:g,1d677:h,1d678:i,1d679:j," +
  "1d67a:k,1d67b:l,1d67c:m,1d67d:n,1d67e:o,1d67f:p,1d680:q,1d681:r,1d682:s,1d683:t,1d684:u,1d685:v,1d686:w," +
  "1d687:x,1d688:y,1d689:z,1d68a:a,1d68b:b,1d68c:c,1d68d:d,1d68e:e,1d68f:f,1d690:g,1d691:h,1d692:i,1d693:j," +
  "1d694:k,1d695:l,1d696:m,1d697:n,1d698:o,1d699:p,1d69a:q,1d69b:r,1d69c:s,1d69d:t,1d69e:u,1d69f:v,1d6a0:w," +
  "1d6a1:x,1d6a2:y,1d6a3:z,1d7ce:0,1d7cf:1,1d7d0:2,1d7d1:3,1d7d2:4,1d7d3:5,1d7d4:6,1d7d5:7,1d7d6:8,1d7d7:9," +
  "1d7d8:0,1d7d9:1,1d7da:2,1d7db:3,1d7dc:4,1d7dd:5,1d7de:6,1d7df:7,1d7e0:8,1d7e1:9,1d7e2:0,1d7e3:1,1d7e4:2," +
  "1d7e5:3,1d7e6:4,1d7e7:5,1d7e8:6,1d7e9:7,1d7ea:8,1d7eb:9,1d7ec:0,1d7ed:1,1d7ee:2,1d7ef:3,1d7f0:4,1d7f1:5," +
  "1d7f2:6,1d7f3:7,1d7f4:8,1d7f5:9,1d7f6:0,1d7f7:1,1d7f8:2,1d7f9:3,1d7fa:4,1d7fb:5,1d7fc:6,1d7fd:7,1d7fe:8," +
  "1d7ff:9,1f12b:c,1f12c:r,1f12d:cd,1f12e:wz,1f130:a,1f131:b,1f132:c,1f133:d,1f134:e,1f135:f,1f136:g,1f137:h," +
  "1f138:i,1f139:j,1f13a:k,1f13b:l,1f13c:m,1f13d:n,1f13e:o,1f13f:p,1f140:q,1f141:r,1f142:s,1f143:t,1f144:u," +
  "1f145:v,1f146:w,1f147:x,1f148:y,1f149:z,1f14a:hv,1f14b:mv,1f14c:sd,1f14d:ss,1f14e:ppv,1f14f:wc,1f16a:mc," +
  "1f16b:md,1f16c:mr,1f190:dj,1fbf0:0,1fbf1:1,1fbf2:2,1fbf3:3,1fbf4:4,1fbf5:5,1fbf6:6,1fbf7:7,1fbf8:8,1fbf9:9";
/** NFKD reads as ASCII letters/digits only after mark removal and full case folding. */
export const COMPAT_MARKED_SIZE = 495;
export const COMPAT_MARKED =
  "c0:a,c1:a,c2:a,c3:a,c4:a,c5:a,c7:c,c8:e,c9:e,ca:e,cb:e,cc:i,cd:i,ce:i,cf:i,d1:n,d2:o,d3:o,d4:o,d5:o,d6:o,d9:u," +
  "da:u,db:u,dc:u,dd:y,e0:a,e1:a,e2:a,e3:a,e4:a,e5:a,e7:c,e8:e,e9:e,ea:e,eb:e,ec:i,ed:i,ee:i,ef:i,f1:n,f2:o,f3:o," +
  "f4:o,f5:o,f6:o,f9:u,fa:u,fb:u,fc:u,fd:y,ff:y,100:a,101:a,102:a,103:a,104:a,105:a,106:c,107:c,108:c,109:c,10a:c," +
  "10b:c,10c:c,10d:c,10e:d,10f:d,112:e,113:e,114:e,115:e,116:e,117:e,118:e,119:e,11a:e,11b:e,11c:g,11d:g,11e:g," +
  "11f:g,120:g,121:g,122:g,123:g,124:h,125:h,128:i,129:i,12a:i,12b:i,12c:i,12d:i,12e:i,12f:i,130:i,134:j,135:j," +
  "136:k,137:k,139:l,13a:l,13b:l,13c:l,13d:l,13e:l,143:n,144:n,145:n,146:n,147:n,148:n,14c:o,14d:o,14e:o,14f:o," +
  "150:o,151:o,154:r,155:r,156:r,157:r,158:r,159:r,15a:s,15b:s,15c:s,15d:s,15e:s,15f:s,160:s,161:s,162:t,163:t," +
  "164:t,165:t,168:u,169:u,16a:u,16b:u,16c:u,16d:u,16e:u,16f:u,170:u,171:u,172:u,173:u,174:w,175:w,176:y,177:y," +
  "178:y,179:z,17a:z,17b:z,17c:z,17d:z,17e:z,1a0:o,1a1:o,1af:u,1b0:u,1c4:dz,1c5:dz,1c6:dz,1cd:a,1ce:a,1cf:i,1d0:i," +
  "1d1:o,1d2:o,1d3:u,1d4:u,1d5:u,1d6:u,1d7:u,1d8:u,1d9:u,1da:u,1db:u,1dc:u,1de:a,1df:a,1e0:a,1e1:a,1e6:g,1e7:g," +
  "1e8:k,1e9:k,1ea:o,1eb:o,1ec:o,1ed:o,1f0:j,1f4:g,1f5:g,1f8:n,1f9:n,1fa:a,1fb:a,200:a,201:a,202:a,203:a,204:e," +
  "205:e,206:e,207:e,208:i,209:i,20a:i,20b:i,20c:o,20d:o,20e:o,20f:o,210:r,211:r,212:r,213:r,214:u,215:u,216:u," +
  "217:u,218:s,219:s,21a:t,21b:t,21e:h,21f:h,226:a,227:a,228:e,229:e,22a:o,22b:o,22c:o,22d:o,22e:o,22f:o,230:o," +
  "231:o,232:y,233:y,1e00:a,1e01:a,1e02:b,1e03:b,1e04:b,1e05:b,1e06:b,1e07:b,1e08:c,1e09:c,1e0a:d,1e0b:d,1e0c:d," +
  "1e0d:d,1e0e:d,1e0f:d,1e10:d,1e11:d,1e12:d,1e13:d,1e14:e,1e15:e,1e16:e,1e17:e,1e18:e,1e19:e,1e1a:e,1e1b:e," +
  "1e1c:e,1e1d:e,1e1e:f,1e1f:f,1e20:g,1e21:g,1e22:h,1e23:h,1e24:h,1e25:h,1e26:h,1e27:h,1e28:h,1e29:h,1e2a:h," +
  "1e2b:h,1e2c:i,1e2d:i,1e2e:i,1e2f:i,1e30:k,1e31:k,1e32:k,1e33:k,1e34:k,1e35:k,1e36:l,1e37:l,1e38:l,1e39:l," +
  "1e3a:l,1e3b:l,1e3c:l,1e3d:l,1e3e:m,1e3f:m,1e40:m,1e41:m,1e42:m,1e43:m,1e44:n,1e45:n,1e46:n,1e47:n,1e48:n," +
  "1e49:n,1e4a:n,1e4b:n,1e4c:o,1e4d:o,1e4e:o,1e4f:o,1e50:o,1e51:o,1e52:o,1e53:o,1e54:p,1e55:p,1e56:p,1e57:p," +
  "1e58:r,1e59:r,1e5a:r,1e5b:r,1e5c:r,1e5d:r,1e5e:r,1e5f:r,1e60:s,1e61:s,1e62:s,1e63:s,1e64:s,1e65:s,1e66:s," +
  "1e67:s,1e68:s,1e69:s,1e6a:t,1e6b:t,1e6c:t,1e6d:t,1e6e:t,1e6f:t,1e70:t,1e71:t,1e72:u,1e73:u,1e74:u,1e75:u," +
  "1e76:u,1e77:u,1e78:u,1e79:u,1e7a:u,1e7b:u,1e7c:v,1e7d:v,1e7e:v,1e7f:v,1e80:w,1e81:w,1e82:w,1e83:w,1e84:w," +
  "1e85:w,1e86:w,1e87:w,1e88:w,1e89:w,1e8a:x,1e8b:x,1e8c:x,1e8d:x,1e8e:y,1e8f:y,1e90:z,1e91:z,1e92:z,1e93:z," +
  "1e94:z,1e95:z,1e96:h,1e97:t,1e98:w,1e99:y,1e9b:s,1ea0:a,1ea1:a,1ea2:a,1ea3:a,1ea4:a,1ea5:a,1ea6:a,1ea7:a," +
  "1ea8:a,1ea9:a,1eaa:a,1eab:a,1eac:a,1ead:a,1eae:a,1eaf:a,1eb0:a,1eb1:a,1eb2:a,1eb3:a,1eb4:a,1eb5:a,1eb6:a," +
  "1eb7:a,1eb8:e,1eb9:e,1eba:e,1ebb:e,1ebc:e,1ebd:e,1ebe:e,1ebf:e,1ec0:e,1ec1:e,1ec2:e,1ec3:e,1ec4:e,1ec5:e," +
  "1ec6:e,1ec7:e,1ec8:i,1ec9:i,1eca:i,1ecb:i,1ecc:o,1ecd:o,1ece:o,1ecf:o,1ed0:o,1ed1:o,1ed2:o,1ed3:o,1ed4:o," +
  "1ed5:o,1ed6:o,1ed7:o,1ed8:o,1ed9:o,1eda:o,1edb:o,1edc:o,1edd:o,1ede:o,1edf:o,1ee0:o,1ee1:o,1ee2:o,1ee3:o," +
  "1ee4:u,1ee5:u,1ee6:u,1ee7:u,1ee8:u,1ee9:u,1eea:u,1eeb:u,1eec:u,1eed:u,1eee:u,1eef:u,1ef0:u,1ef1:u,1ef2:y," +
  "1ef3:y,1ef4:y,1ef5:y,1ef6:y,1ef7:y,1ef8:y,1ef9:y,212b:a,1d6a6:ss,1df95:ss";
