import { readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { CONFUSABLE_SKELETON } from "./confusables.js";
import { UTS39_SKELETON } from "./confusables-data.js";
import { forbiddenTermsIn } from "./sessions.js";

describe("forbidden-term confusables", () => {
  it("is generated from UTS #39 with its version and source hash recorded", () => {
    const data = readFileSync(path.join(import.meta.dirname, "confusables-data.ts"), "utf8");
    expect(data).toMatch(/^\/\/ GENERATED by scripts\/generate-confusables\.ts/u);
    expect(data).toMatch(/UTS #39 confusables\.txt, version \d+\.\d+\.\d+ .*sha256 [0-9a-f]{64}/u);
    expect(Object.keys(UTS39_SKELETON).length).toBeGreaterThan(1500);
  });

  it("lets UTS #39 win over the hand tables where both have an entry", () => {
    for (const [char, skeleton] of [["η", "h"], ["μ", "m"], ["ν", "n"], ["б", "6"]] as const) {
      expect(CONFUSABLE_SKELETON[char], char).toBe(skeleton);
    }
  });

  it("keeps hand lookalikes that UTS #39 does not list (small capitals)", () => {
    expect(CONFUSABLE_SKELETON["ᴀ"]).toBe("a");
    expect(CONFUSABLE_SKELETON["ʙ"]).toBe("b");
  });

  it("matches common Cyrillic, Greek and stroked-Latin smuggling of a forbidden term", () => {
    for (const text of ["sесrеt plan", "ѕecret plan", "secreτ plan", "secret pƖan"]) {
      expect(forbiddenTermsIn(text, ["secret"]), text).toEqual(["secret"]);
    }
    expect(forbiddenTermsIn("a perfectly normal sentence", ["secret"])).toEqual([]);
  });
});
