import { readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { CONFUSABLE_SKELETON, HAND_FIRST_SKELETON } from "./confusables.js";
import { UTS39_SKELETON } from "./confusables-data.js";
import { MAIN_SNAPSHOT, MAIN_SNAPSHOT_SIZE } from "./confusables-main-snapshot.js";
import { forbiddenTermsIn } from "./sessions.js";

describe("forbidden-term confusables", () => {
  it("is generated from UTS #39 with its version and source hash recorded", () => {
    const data = readFileSync(path.join(import.meta.dirname, "confusables-data.ts"), "utf8");
    expect(data).toMatch(/^\/\/ GENERATED by scripts\/generate-confusables\.ts/u);
    expect(data).toMatch(/UTS #39 confusables\.txt, version \d+\.\d+\.\d+ .*sha256 [0-9a-f]{64}/u);
    expect(Object.keys(UTS39_SKELETON).length).toBeGreaterThan(1500);
  });

  it("keeps Unicode's direct lowercase entries (a capital never overwrites its lowercase letter)", () => {
    for (const [char, skeleton] of [["η", "n"], ["ν", "v"], ["Η", "h"], ["Ν", "n"], ["Μ", "m"], ["б", "6"]] as const) {
      expect(UTS39_SKELETON[char], char).toBe(skeleton);
    }
  });

  it("catches Greek and Cyrillic capitals and lowercase letters both ways (dual skeleton)", () => {
    const cases: Array<[string, string]> = [
      ["Μoney", "money"], ["μoney", "uoney"], ["ΗELLO", "hello"], ["ηame", "name"], ["Νew", "new"], ["νery", "very"],
      ["Υes", "yes"], ["υse", "use"], ["Вig", "big"], ["Нome", "home"], ["Мap", "map"], ["Тop", "top"], ["Сat", "cat"],
    ];
    for (const [text, term] of cases) expect(forbiddenTermsIn(text, [term]), `${text} vs ${term}`).toEqual([term]);
  });

  it("keeps every hand Greek/Cyrillic reading reachable through the hand-first table", () => {
    for (const [char, skeleton] of Object.entries({ μ: "u", η: "n", ν: "v", б: "b" })) {
      expect(HAND_FIRST_SKELETON[char], char).toBe(skeleton);
    }
  });

  it("keeps hand lookalikes that UTS #39 does not list (small capitals)", () => {
    expect(CONFUSABLE_SKELETON["ᴀ"]).toBe("a");
    expect(CONFUSABLE_SKELETON["ʙ"]).toBe("b");
  });

  it("matches common Cyrillic, Greek and stroked-Latin smuggling of a forbidden term", () => {
    for (const text of ["sесrеt plan", "ѕecret plan", "secreτ plan", "secret pƖan", "secret pɩan"]) {
      expect(forbiddenTermsIn(text, ["secret"]), text).toEqual(["secret"]);
    }
    expect(forbiddenTermsIn("a perfectly normal sentence", ["secret"])).toEqual([]);
    // Re-review follow-ups: Cherokee Ꮤ (both cases) folds to w, Latin Ɩ to l.
    for (const text of ["Ꮤell done", "ꮤell done"]) expect(forbiddenTermsIn(text, ["well"]), text).toEqual(["well"]);
    expect(forbiddenTermsIn("pƖan", ["plan"])).toEqual(["plan"]);
  });

  it("catches digit lookalikes (0 for o, 1 for l) and still matches terms that contain digits", () => {
    expect(forbiddenTermsIn("the pr0ject plan", ["project"])).toEqual(["project"]);
    expect(forbiddenTermsIn("a 1eak happened", ["leak"])).toEqual(["leak"]);
    expect(forbiddenTermsIn("order 1001 shipped", ["1001"])).toEqual(["1001"]);
    expect(forbiddenTermsIn("an ordinary sentence", ["project"])).toEqual([]);
  });

  it("matches words that mix letters needing different modes or tables (per-character readings)", () => {
    const cases: Array<[string, string]> = [
      ["ΙΝVEST now", "invest"], ["ΗΙDDEΝ fee", "hidden"], ["ΝΙCE", "nice"], ["ΗΙRE", "hire"], ["ΥΙELD", "yield"],
      ["ΗЦnt", "hunt"], ["баd", "bad"], ["ｉｎｖｅｓｔ", "invest"], ["ínvést", "invest"], ["in\u034Fvest", "invest"],
      ["in\u200Dvest", "invest"], ["i\u00ADnvest", "invest"], ["pr0ject", "project"], ["ΡR0JΕСТ", "project"],
      ["buß", "bus"], ["ßun", "sun"], ["moы", "mob"], ["æon", "eon"], ["pæ", "pa"],
    ];
    for (const [text, term] of cases) expect(forbiddenTermsIn(text, [term]), `${text} vs ${term}`).toEqual([term]);
    expect(forbiddenTermsIn("nothing to see here", ["invest", "hidden", "hire"])).toEqual([]);
  });

  // Snapshot of the mapping before this PR (origin/main db9c8ed): every key stays in the generated table, and its old
  // prototype stays a reading of it (some prototypes changed, e.g. Greek beta -> "ss"; the hand table keeps "b").
  it("loses no confusable from the previous mapping (origin/main snapshot)", () => {
    const snapshot = MAIN_SNAPSHOT.split(",").map((entry) => {
      const [from, to] = entry.split(":");
      return [String.fromCodePoint(Number.parseInt(from!, 16)), to!] as const;
    });
    expect(snapshot.length).toBe(MAIN_SNAPSHOT_SIZE);
    expect(snapshot.length).toBe(2149);
    const missing = snapshot.filter(([char]) => UTS39_SKELETON[char] === undefined).map(([char]) => char.codePointAt(0)!.toString(16));
    expect(missing).toEqual([]);
    const lost = snapshot
      .filter(([char, prototype]) => forbiddenTermsIn(`qz${char}zq`, [`qz${prototype}zq`]).length !== 1)
      .map(([char, prototype]) => `${char.codePointAt(0)!.toString(16)}:${prototype}`);
    expect(lost).toEqual([]);
  });

  // Dotless ı (U+0131) and dotted İ (U+0130): both read "i", in text and in terms, in either case. İ lowercases to
  // i + U+0307 and folds the same way (CaseFolding.txt F; the Turkic T entries are not used); ı reads "i" through the
  // UTS #39 and hand tables. İ also reads "l" (its NFD base I is the UTS #39 lookalike of l); ı does not. Over-matching
  // is accepted; İ is not a lookalike for e.
  it("reads dotless ı and dotted İ as i (current behaviour)", () => {
    const matches: Array<[string, string]> = [
      ["ıd", "id"], ["İd", "id"], ["İD", "id"], ["admın", "admin"], ["ADMİN", "admin"], ["admİn", "admin"], ["secrİt", "secrit"],
      ["KİŞİ", "kisi"], ["DIŞ", "dis"], ["İd", "ld"], ["admin", "admİn"], ["admin", "admın"], ["id", "ıd"], ["ld", "İd"],
    ];
    for (const [text, term] of matches) expect(forbiddenTermsIn(text, [term]), `${text} vs ${term}`).toEqual([term]);
    for (const [text, term] of [["secrİt", "secret"], ["ıd", "ld"]] as const) {
      expect(forbiddenTermsIn(text, [term]), `${text} vs ${term}`).toEqual([]);
    }
  });

  // Cherokee Ᏸ / ᏸ (U+13F0 / U+13F8): UTS #39 maps them to sharp s ("ss" after folding); the hand table adds "b",
  // like Latin small beta ꞵ.
  it("reads Cherokee Ᏸ / ᏸ as both b and ss", () => {
    for (const char of ["\u{13F0}", "\u{13F8}"]) {
      expect(forbiddenTermsIn(`${char}et`, ["bet"]), char).toEqual(["bet"]);
      expect(forbiddenTermsIn(`${char}et`, ["sset"]), char).toEqual(["sset"]);
    }
  });

  it("stays within a time budget at the grant maxima (64 terms × 200 chars, 4096-char text)", () => {
    const alphabet = [..."ΙΝΗΥΜΤΒΕΚΡСОАНВМТаеорсухьbcdfghjklmnpqrstvwxyz0123456789 ".normalize("NFC")];
    let seed = 7;
    const random = () => (seed = (seed * 1103515245 + 12345) % 2147483648) / 2147483648;
    const pick = (length: number) => Array.from({ length }, () => alphabet[Math.floor(random() * alphabet.length)]).join("");
    const terms = Array.from({ length: 64 }, () => pick(200).replace(/ /gu, "x"));
    const text = pick(4096);
    const started = performance.now();
    forbiddenTermsIn(text, terms);
    expect(performance.now() - started).toBeLessThan(5000);
  });
});

