import { readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { CONFUSABLE_SKELETON, HAND_FIRST_SKELETON } from "./confusables.js";
import { UTS39_SKELETON } from "./confusables-data.js";
import { forbiddenTermsIn } from "./sessions.js";

describe("forbidden-term confusables", () => {
  it("is generated from UTS #39 with its version and source hash recorded", () => {
    const data = readFileSync(path.join(import.meta.dirname, "confusables-data.ts"), "utf8");
    expect(data).toMatch(/^\/\/ GENERATED by scripts\/generate-confusables\.ts/u);
    expect(data).toMatch(/UTS #39 confusables\.txt, version \d+\.\d+\.\d+ .*sha256 [0-9a-f]{64}/u);
    expect(Object.keys(UTS39_SKELETON).length).toBeGreaterThan(1500);
  });

  it("keeps Unicode's direct lowercase entries (a capital never overwrites its lowercase letter)", () => {
    for (const [char, skeleton] of [["η", "n"], ["ν", "v"], ["Η", "h"], ["Ν", "n"], ["Μ", "m"], ["б", "6"]] as const) {
      expect(UTS39_SKELETON[char], char).toBe(skeleton);
    }
  });

  it("catches Greek and Cyrillic capitals and lowercase letters both ways (dual skeleton)", () => {
    const cases: Array<[string, string]> = [
      ["Μoney", "money"], ["μoney", "uoney"], ["ΗELLO", "hello"], ["ηame", "name"], ["Νew", "new"], ["νery", "very"],
      ["Υes", "yes"], ["υse", "use"], ["Вig", "big"], ["Нome", "home"], ["Мap", "map"], ["Тop", "top"], ["Сat", "cat"],
    ];
    for (const [text, term] of cases) expect(forbiddenTermsIn(text, [term]), `${text} vs ${term}`).toEqual([term]);
  });

  it("keeps every hand Greek/Cyrillic reading reachable through the hand-first table", () => {
    for (const [char, skeleton] of Object.entries({ μ: "u", η: "n", ν: "v", б: "b" })) {
      expect(HAND_FIRST_SKELETON[char], char).toBe(skeleton);
    }
  });

  it("keeps hand lookalikes that UTS #39 does not list (small capitals)", () => {
    expect(CONFUSABLE_SKELETON["ᴀ"]).toBe("a");
    expect(CONFUSABLE_SKELETON["ʙ"]).toBe("b");
  });

  it("matches common Cyrillic, Greek and stroked-Latin smuggling of a forbidden term", () => {
    for (const text of ["sесrеt plan", "ѕecret plan", "secreτ plan", "secret pƖan", "secret pɩan"]) {
      expect(forbiddenTermsIn(text, ["secret"]), text).toEqual(["secret"]);
    }
    expect(forbiddenTermsIn("a perfectly normal sentence", ["secret"])).toEqual([]);
    // Re-review follow-ups: Cherokee Ꮤ (both cases) folds to w, Latin Ɩ to l.
    for (const text of ["Ꮤell done", "ꮤell done"]) expect(forbiddenTermsIn(text, ["well"]), text).toEqual(["well"]);
    expect(forbiddenTermsIn("pƖan", ["plan"])).toEqual(["plan"]);
  });
});
