/**
 * Company Box coverage: for every catalog entry, every operation (openapi)
 * or tool (mcp) in the vendored, pinned snapshot is either exposed or
 * excluded with a reason. Anything else fails the report.
 */
import fs from "node:fs";
import path from "node:path";

import {
  companyBoxListing,
  loadCompanyBoxCatalog,
  type CompanyBoxCoverageItem,
  type CompanyBoxLoadError,
  type CompiledCompanyBoxEntry,
} from "./company-box.js";

export type CompanyBoxCoverageEntry = {
  id: string;
  displayName: string;
  source: "openapi" | "mcp";
  appVersion: string;
  pinnedSha256: string;
  exposure: "direct" | "discovery";
  total: number;
  exposed: number;
  excluded: number;
  failed: number;
  outward: number;
  destructive: number;
  ok: boolean;
  errors: string[];
  warnings: string[];
  items: CompanyBoxCoverageItem[];
};

export type CompanyBoxCoverageReport = {
  schema: 1;
  ok: boolean;
  totals: { entries: number; operations: number; exposed: number; excluded: number };
  entries: CompanyBoxCoverageEntry[];
  loadErrors: CompanyBoxLoadError[];
};

function coverageEntry(compiled: CompiledCompanyBoxEntry): CompanyBoxCoverageEntry {
  const items = compiled.coverage;
  const total = items.length;
  const exposed = items.filter((item) => item?.status === "exposed").length;
  const excluded = items.filter((item) => item?.status === "excluded").length;
  const failed = items.filter((item) => item?.status === "failed").length;
  const errors = [...compiled.errors];
  if (items.some((item) => item === undefined)) {
    errors.push("Some operations have no coverage status.");
  }
  if (exposed + excluded !== total) {
    errors.push(`Exposed (${exposed}) + excluded (${excluded}) must equal the ${total} operations in the pinned spec.`);
  }
  if (compiled.kind === "openapi") {
    const listing = companyBoxListing(compiled);
    if (listing.actions.length !== exposed || new Set(listing.actions).size !== exposed) {
      errors.push(`The listing publishes ${listing.actions.length} actions for ${exposed} exposed operations.`);
    }
  } else if (compiled.tools.length !== exposed) {
    errors.push(`${compiled.tools.length} tools are exposed for ${exposed} exposed snapshot tools.`);
  }
  return {
    id: compiled.entry.id,
    displayName: compiled.entry.displayName,
    source: compiled.kind,
    appVersion: compiled.entry.app.version,
    pinnedSha256: compiled.kind === "openapi" ? compiled.specSha256 : compiled.snapshotSha256,
    exposure: compiled.exposure,
    total,
    exposed,
    excluded,
    failed,
    outward: items.filter((item) => item?.outward).length,
    destructive: items.filter((item) => item?.destructive).length,
    ok: errors.length === 0,
    errors,
    warnings: compiled.warnings,
    items,
  };
}

export function companyBoxCoverageReport(
  dir: string,
  options: { directMaxOperations?: number } = {},
): CompanyBoxCoverageReport {
  const catalog = loadCompanyBoxCatalog(dir, options);
  const entries = catalog.entries
    .map(coverageEntry)
    .sort((left, right) => left.id.localeCompare(right.id));
  return {
    schema: 1,
    ok: catalog.loadErrors.length === 0 && entries.every((entry) => entry.ok),
    totals: {
      entries: entries.length,
      operations: entries.reduce((sum, entry) => sum + entry.total, 0),
      exposed: entries.reduce((sum, entry) => sum + entry.exposed, 0),
      excluded: entries.reduce((sum, entry) => sum + entry.excluded, 0),
    },
    entries,
    loadErrors: catalog.loadErrors,
  };
}

function cell(value: string) {
  return value.replace(/\|/gu, "\\|").replace(/\r?\n/gu, " ");
}

export function companyBoxCoverageMarkdown(report: CompanyBoxCoverageReport) {
  const lines = [
    "# Company Box coverage",
    "",
    "Generated by `pnpm run company-box:coverage`. Do not edit by hand.",
    "",
    `Status: **${report.ok ? "pass" : "FAIL"}** — ${report.totals.entries} entries, ${report.totals.exposed}/${report.totals.operations} operations exposed, ${report.totals.excluded} excluded with a reason.`,
    "",
  ];
  if (report.entries.length) {
    lines.push(
      "| Entry | Source | App version | Exposed | Excluded | Exposure | Outward | Destructive | Status |",
      "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
      ...report.entries.map(
        (entry) =>
          `| ${cell(entry.displayName)} (\`${entry.id}\`) | ${entry.source} | ${cell(entry.appVersion)} | ${entry.exposed}/${entry.total} | ${entry.excluded} | ${entry.exposure} | ${entry.outward} | ${entry.destructive} | ${entry.ok ? "pass" : "FAIL"} |`,
      ),
      "",
    );
  } else {
    lines.push("No entries yet.", "");
  }
  for (const error of report.loadErrors) {
    lines.push(`- **${error.entry}** could not load (${error.code}): ${cell(error.message)}`);
  }
  if (report.loadErrors.length) lines.push("");
  for (const entry of report.entries) {
    lines.push(`## ${entry.displayName} (\`${entry.id}\`)`, "");
    lines.push(`Pinned ${entry.source === "openapi" ? "spec" : "tools snapshot"} sha256 \`${entry.pinnedSha256}\`.`, "");
    for (const error of entry.errors) lines.push(`- Error: ${cell(error)}`);
    for (const warning of entry.warnings) lines.push(`- Warning: ${cell(warning)}`);
    if (entry.errors.length || entry.warnings.length) lines.push("");
    const excluded = entry.items.filter((item) => item?.status !== "exposed");
    if (excluded.length) {
      lines.push("| Operation | Status | Reason |", "| --- | --- | --- |");
      for (const item of excluded) {
        lines.push(`| ${cell(item.ref)} | ${item.status} | ${cell(item.reason ?? "(missing)")} |`);
      }
      lines.push("");
    }
    lines.push(
      "<details><summary>Exposed operations</summary>",
      "",
      "| Operation | Action key | Capability | Flags |",
      "| --- | --- | --- | --- |",
      ...entry.items
        .filter((item) => item?.status === "exposed")
        .map(
          (item) =>
            `| ${cell(item.method ? `${item.method} ${item.path}` : item.ref)}${item.method && item.ref !== `${item.method} ${item.path}` ? ` (\`${cell(item.ref)}\`)` : ""} | \`${item.key}\` | ${item.capability} | ${[item.outward ? "outward" : "", item.destructive ? "destructive" : ""].filter(Boolean).join(", ")} |`,
        ),
      "",
      "</details>",
      "",
    );
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function writeCompanyBoxCoverage(report: CompanyBoxCoverageReport, outDir: string) {
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "coverage.json"), `${JSON.stringify(report, null, 2)}\n`);
  fs.writeFileSync(path.join(outDir, "COVERAGE.md"), companyBoxCoverageMarkdown(report));
}

/** CLI: `company-box:coverage [--dir <catalog>] [--out <dir>] [--no-write]`. Returns the exit code. */
export function runCompanyBoxCoverageCli(
  argv: readonly string[],
  defaults: { dir: string },
  log: (line: string) => void = console.log,
) {
  let dir = defaults.dir;
  let out: string | null = null;
  let write = true;
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--dir") dir = path.resolve(argv[++index] ?? "");
    else if (arg === "--out") out = path.resolve(argv[++index] ?? "");
    else if (arg === "--no-write") write = false;
    else {
      log(`Unknown argument ${arg}. Usage: company-box:coverage [--dir <catalog>] [--out <dir>] [--no-write]`);
      return 2;
    }
  }
  const report = companyBoxCoverageReport(dir);
  if (write) writeCompanyBoxCoverage(report, out ?? dir);
  for (const entry of report.entries) {
    log(`${entry.ok ? "ok  " : "FAIL"} ${entry.id}: ${entry.exposed}/${entry.total} exposed, ${entry.excluded} excluded (${entry.exposure})`);
    for (const error of entry.errors) log(`     error: ${error}`);
  }
  for (const error of report.loadErrors) log(`FAIL ${error.entry}: ${error.code}: ${error.message}`);
  log(
    `${report.ok ? "Coverage passed" : "Coverage FAILED"}: ${report.totals.exposed}/${report.totals.operations} operations exposed across ${report.totals.entries} entries.`,
  );
  return report.ok ? 0 : 1;
}
