import { MARKETPLACE_VERSION } from "./version.js";

const jsonObject = { type: "object", additionalProperties: true } as const;
const bearerSecurity = [{ bearerAuth: [] }] as const;
const operatorSecurity = [{ operatorSession: [] }] as const;

export function buildMarketplaceOpenApi(baseUrl = "/") {
  return {
    openapi: "3.1.0",
    info: {
      title: "Teal Brick Marketplace API",
      version: MARKETPLACE_VERSION,
      description:
        "Program-owned catalog, Rules-governed plugin lifecycle, provider connections, capability bindings, Composio execution, and audit. The launch profile treats every non-Composio source as catalog-only. Hub and cross-app service routes require an internal bearer credential that is never exposed to the browser.",
    },
    servers: [{ url: baseUrl }],
    security: operatorSecurity,
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          description: "Internal HDDA Host SDK or cross-app service credential.",
        },
        operatorSession: {
          type: "apiKey",
          in: "cookie",
          name: "dg_marketplace_operator_session",
          description: "Short-lived HttpOnly operator session. Browser mutations also require the per-session x-csrf-token header.",
        },
      },
    },
    tags: [
      { name: "Runtime" },
      { name: "Catalog" },
      { name: "Lifecycle" },
      { name: "Connections" },
      { name: "Bindings" },
      { name: "Execution" },
      { name: "Audit" },
      { name: "Provider settings" },
      { name: "Custom connectors" },
      { name: "Company Box" },
      { name: "Hub service" },
      { name: "Agent" },
    ],
    paths: {
      "/healthz": { get: { security: [], tags: ["Runtime"], summary: "Program liveness", responses: { "200": { description: "Healthy" } } } },
      "/status": { get: { security: [], tags: ["Runtime"], summary: "Redacted frontend-safe status", responses: { "200": { description: "Status" } } } },
      "/bootstrap.json": { get: { security: [], tags: ["Runtime"], summary: "Redacted frontend bootstrap and authorization posture", responses: { "200": { description: "Bootstrap" } } } },
      "/auth/launch": { post: { security: [], tags: ["Runtime"], summary: "Redeem a Portal one-use browser launch ticket", description: "Accepts the Portal form POST, redeems the ticket server-to-server with the configured deployment identity, stores the attested Portal handoff session without echoing the ticket, issues the existing HttpOnly Marketplace operator session, and redirects to the UI.", requestBody: { required: true, content: { "application/x-www-form-urlencoded": { schema: { type: "object", additionalProperties: false, required: ["ticket"], properties: { ticket: { type: "string", writeOnly: true, pattern: "^[A-Za-z0-9_-]{43}$" } } } } } }, responses: { "303": { description: "Marketplace operator session created; redirect to the UI" }, "401": { description: "Invalid, duplicate, or replayed ticket" }, "403": { description: "Portal Origin or deployment identity denied" }, "503": { description: "Portal handoff is not configured or unavailable" } } } },
      "/api/marketplace/auth/session": {
        get: { security: [], tags: ["Runtime"], summary: "Read the redacted operator-session state", responses: { "200": { description: "Session status" } } },
        post: { security: [], tags: ["Runtime"], summary: "Exchange the provisioned operator access token for an HttpOnly session", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["accessToken"], properties: { accessToken: { type: "string", writeOnly: true } } } } } }, responses: { "200": { description: "Session created" }, "401": { description: "Invalid token" }, "429": { description: "Rate limited" }, "503": { description: "Operator access is not configured" } } },
        delete: { security: operatorSecurity, tags: ["Runtime"], summary: "Revoke the current operator session", responses: { "200": { description: "Session revoked" }, "401": { description: "Unauthorized" } } },
      },
      "/api/status": { get: { security: bearerSecurity, tags: ["Runtime"], summary: "Detailed Program status (internal service bearer only)", responses: { "200": { description: "Runtime status" } } } },
      "/api/marketplace/health": { get: { security: [...operatorSecurity, ...bearerSecurity], tags: ["Runtime"], summary: "Authenticated runtime health: Program and Rules connection state", description: "Returns { program: 'ok', rules: 'connected' | 'not-connected' | 'unavailable' }. The Rules probe is cached briefly and never returns configuration or credentials.", responses: { "200": { description: "Runtime health" }, "401": { description: "Session or bearer required" } } } },
      "/api/marketplace/cards": { get: { tags: ["Catalog"], summary: "List operator-facing plugin cards", parameters: [{ name: "workspaceSlug", in: "query", schema: { type: "string", default: "default" } }], responses: { "200": { description: "Cards and provider state" } } } },
      "/api/marketplace/cards/summary": { get: { tags: ["Catalog"], summary: "List a bounded, searchable browser-safe catalog projection", description: "Returns exact catalog totals, redacted provider and connection status, and at most 100 lightweight records from the canonical Marketplace catalog. Arbitrary manifests and provider metadata are omitted.", parameters: [{ name: "workspaceSlug", in: "query", schema: { type: "string", default: "default" } }, { name: "search", in: "query", schema: { type: "string", maxLength: 200 } }, { name: "source", in: "query", schema: { type: "string", enum: ["all", "native", "activepieces", "composio", "nango", "mcp"], default: "all" } }, { name: "installed", in: "query", schema: { type: "boolean", default: false } }, { name: "offset", in: "query", schema: { type: "integer", minimum: 0, default: 0 } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 60 } }], responses: { "200": { description: "Bounded browser-safe catalog projection" } } } },
      "/api/marketplace/cards/{pluginId}": { get: { tags: ["Catalog"], summary: "Read one browser-safe operator card", description: "Returns the selected card's UI contract without arbitrary manifest, connection metadata, credentials, environment, or runtime endpoint fields.", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }, { name: "workspaceSlug", in: "query", schema: { type: "string", default: "default" } }], responses: { "200": { description: "Redacted operator card and provider status" }, "404": { description: "Not found" } } } },
      "/api/marketplace/plugins": { get: { tags: ["Catalog"], summary: "List catalog records with workspace state", parameters: [{ name: "workspaceSlug", in: "query", schema: { type: "string", default: "default" } }], responses: { "200": { description: "Plugins" } } } },
      "/api/marketplace/plugins/{pluginId}": { get: { tags: ["Catalog"], summary: "Read one plugin", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }, { name: "workspaceSlug", in: "query", schema: { type: "string" } }], responses: { "200": { description: "Plugin" }, "404": { description: "Not found" } } } },
      "/api/marketplace/plugins/{pluginId}/install": { post: { tags: ["Lifecycle"], summary: "Rules-governed install", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "201": { description: "Installed" }, "403": { description: "Rules denied" }, "503": { description: "Rules unavailable" } } } },
      "/api/marketplace/plugins/{pluginId}/uninstall": { post: { tags: ["Lifecycle"], summary: "Rules-governed uninstall", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "200": { description: "Uninstalled" }, "409": { description: "Required or not installed" } } } },
      "/api/marketplace/plugins/{pluginId}/register": { post: { tags: ["Lifecycle"], summary: "Register with the plugin runtime", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "201": { description: "Registered" } } } },
      "/api/marketplace/plugins/{pluginId}/unregister": { post: { tags: ["Lifecycle"], summary: "Unregister from the plugin runtime", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "200": { description: "Unregistered" }, "409": { description: "Required plugin" } } } },
      "/api/marketplace/plugins/{pluginId}/connection": { post: { tags: ["Connections"], summary: "Start or register a provider connection", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "200": { description: "Connection or OAuth redirect" }, "409": { description: "Provider unavailable" } } } },
      "/api/marketplace/plugins/{pluginId}/capability-binding": { post: { tags: ["Bindings"], summary: "Set a Rules-governed capability binding", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "201": { description: "Bound" } } } },
      "/api/marketplace/plugins/{pluginId}/action-binding": { post: { tags: ["Bindings"], summary: "Include or exclude an Agent action", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "201": { description: "Bound" } } } },
      "/api/marketplace/plugins/{pluginId}/execute": { post: { tags: ["Execution"], summary: "Execute one enabled and connected Composio or custom MCP action through Rules", description: "The launch profile executes Composio-backed actions and the workspace's own custom MCP connectors. Other catalog sources return 501 and are never recorded as successful usage. MCP tool errors return 502 mcp_tool_failed; transport failures return 502 mcp_unreachable. Operator frontends must confirm the impact before sending.", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "200": { description: "Executed through Composio" }, "403": { description: "Rules or binding denied" }, "409": { description: "Not installed or connected" }, "501": { description: "Catalog source is not executable in this launch profile" }, "502": { description: "Provider failed" } } } },
      "/api/marketplace/connectors/custom": {
        get: { security: operatorSecurity, tags: ["Custom connectors"], summary: "List this workspace's custom MCP connectors", description: "Browser-safe views: server origin and path, plain header names and values, secret headers as { name, configured, fingerprint }, discovered tools with capabilities, last refresh, install and connection state. Secret values are never returned.", responses: { "200": { description: "Custom connectors" }, "403": { description: "Operator session required" } } },
        post: { security: operatorSecurity, tags: ["Custom connectors"], summary: "Add a remote MCP server as a custom connector", description: "Rules-governed (connector.admin, custom-mcp.create). HTTPS streamable-http or SSE servers only; stdio, command, args, env, and cwd are refused. Secret header values are encrypted at rest.", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["displayName", "url"], properties: { displayName: { type: "string", maxLength: 80 }, slug: { type: "string", maxLength: 40 }, description: { type: "string", maxLength: 500 }, transport: { type: "string", enum: ["streamable-http", "sse"], default: "streamable-http" }, url: { type: "string", format: "uri" }, headers: { type: "object", additionalProperties: { type: "string" } }, secretHeaders: { type: "object", additionalProperties: { type: "string", writeOnly: true } } } } } } }, responses: { "201": { description: "Created" }, "400": { description: "Invalid input, URL not allowed, or stdio transport refused" }, "403": { description: "Rules denied" }, "409": { description: "Already exists or Rules review required" }, "503": { description: "Rules or the secret store is unavailable" } } },
      },
      "/api/marketplace/connectors/custom/{pluginId}": {
        patch: { security: operatorSecurity, tags: ["Custom connectors"], summary: "Edit a custom connector", description: "secretHeaders values: string replaces, null removes, omitted keeps. Changing the URL or transport disconnects the connector and clears its tools until the next refresh.", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "200": { description: "Updated" }, "404": { description: "Not found in this workspace" } } },
        delete: { security: operatorSecurity, tags: ["Custom connectors"], summary: "Delete a custom connector", description: "Removes the install, bindings, connection, secrets and credential references, and revokes broker grants and agent grants or consents for it.", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Deleted" }, "404": { description: "Not found in this workspace" } } },
      },
      "/api/marketplace/connectors/custom/{pluginId}/refresh": { post: { security: operatorSecurity, tags: ["Custom connectors"], summary: "Connect to the MCP server and load its tools", description: "Runs initialize and tools/list (up to 200 tools), derives action keys and capabilities, and marks the connection connected. Failures return a safe error code and record it as the last refresh.", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Tools refreshed" }, "400": { description: "Server address not allowed" }, "502": { description: "MCP server unreachable or rejected the request" } } } },
      "/api/marketplace/company-box": { get: { security: operatorSecurity, tags: ["Company Box"], summary: "List the Company Box collection", description: "Curated self-hosted app connectors with full-API coverage (exposed/excluded operations), exposure mode, auth fields, and this workspace's install, connection and credential state (names and fingerprints only).", responses: { "200": { description: "Collection" } } } },
      "/api/marketplace/company-box/{entryId}/setup": { post: { security: operatorSecurity, tags: ["Company Box"], summary: "Install and configure an entry for the workspace", description: "Validates the base URL with the outbound URL policy (tailnet allowed), stores credentials in the encrypted connector secret store (omitted fields keep their value), installs once for the workspace and runs the entry's connection test. mcp entries install through the custom remote MCP path.", parameters: [{ name: "entryId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["baseUrl"], properties: { baseUrl: { type: "string" }, credentials: { type: "object", additionalProperties: { type: "string", writeOnly: true } } } } } } }, responses: { "200": { description: "Configured and connected" }, "400": { description: "Address or credentials invalid" }, "502": { description: "Configured, but the connection test failed" } } } },
      "/api/marketplace/company-box/{entryId}/test": { post: { security: operatorSecurity, tags: ["Company Box"], summary: "Re-run the connection test", parameters: [{ name: "entryId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Connected" }, "409": { description: "Not set up" }, "502": { description: "Test failed" } } } },
      "/api/marketplace/company-box/{entryId}": { delete: { security: operatorSecurity, tags: ["Company Box"], summary: "Remove an entry from the workspace", description: "Uninstalls, deletes stored credentials and revokes agent grants and consents for the entry.", parameters: [{ name: "entryId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Removed" } } } },
      "/api/marketplace/provider-health": { get: { tags: ["Connections"], summary: "Probe configured provider reachability", responses: { "200": { description: "Provider state" } } } },
      "/api/marketplace/audit": { get: { tags: ["Audit"], summary: "List lifecycle audit and usage evidence", parameters: [{ name: "workspaceSlug", in: "query", schema: { type: "string" } }, { name: "limit", in: "query", schema: { type: "integer", default: 100 } }], responses: { "200": { description: "Audit" } } } },
      "/api/settings/providers/composio": {
        get: { security: operatorSecurity, tags: ["Provider settings"], summary: "Read redacted Composio settings", responses: { "200": { description: "Redacted settings" } } },
        put: { security: operatorSecurity, tags: ["Provider settings"], summary: "Persist allowlisted Composio settings and an optional API key", requestBody: { required: true, content: { "application/json": { schema: { type: "object", properties: { settings: { type: "object", properties: { composioApiKey: { type: "string", writeOnly: true }, composioBaseUrl: { type: "string", format: "uri" }, composioDefaultUserId: { type: "string" }, composioDefaultConnectedAccountId: { type: "string" } } } } } } } }, responses: { "200": { description: "Saved redacted settings" }, "400": { description: "Provider origin is not allowlisted" } } },
      },
      "/api/settings/providers/composio/test": { post: { security: operatorSecurity, tags: ["Provider settings"], summary: "Check a Composio API key against the allowlisted Composio host", description: "Tests the saved key, or an unsaved key in the body, with one read-only request to an https://*.composio.dev base URL. The key is never returned. Records an audit event.", requestBody: { required: false, content: { "application/json": { schema: { type: "object", properties: { composioApiKey: { type: "string", writeOnly: true } } } } } }, responses: { "200": { description: "Key accepted" }, "400": { description: "No key, malformed key, or base URL not allowed" }, "422": { description: "Composio rejected the key" }, "502": { description: "Composio unreachable" } } } },
      "/api/settings/providers/composio/key": { delete: { security: operatorSecurity, tags: ["Provider settings"], summary: "Remove the Program-stored Composio API key", description: "Records an audit event. A key supplied by the deployment environment cannot be removed here (409).", responses: { "200": { description: "Removed (or already absent)" }, "409": { description: "Key managed by the deployment environment" } } } },
      "/api/agent/capabilities": { get: { tags: ["Agent"], summary: "List enabled Composio and custom MCP tools currently projected to Agents", description: "Custom MCP connectors are projected after a successful tool refresh. Native, Activepieces, Nango, and Hub MCP records are catalog-only and are not projected as executable Agent tools in this launch profile.", parameters: [{ name: "workspaceSlug", in: "query", schema: { type: "string", default: "default" } }], responses: { "200": { description: "Capabilities" } } } },
      "/api/marketplace/v1/agent/action-catalog": { get: { security: [...operatorSecurity, ...bearerSecurity], tags: ["Agent"], summary: "List the agent actions this workspace currently publishes", description: "Contract doppelganger.marketplace.agent-action-catalog.v1. Returns { contractVersion, workspaceSlug, actions[] } where each action is { pluginId, pluginName, provider, actionKey, label, description, capability, resourceKind, mode: 'connected-account', accounts: [{ accountId, label? }], allowedArguments: string[] | null, toolName }. An action is listed only while its connector is registered, installed and enabled, executable for agents, connected, the action is enabled, and its capability binding is enabled. Portal selections, consents, grants and runtime calls resolve against this same live catalog. Secrets, connection metadata beyond the account id and label, and raw manifests are never returned. Operator sessions are scoped to their organization; the internal service bearer must pass workspaceSlug.", parameters: [{ name: "workspaceSlug", in: "query", required: false, description: "Must equal the caller's organization. Required for the service bearer.", schema: { type: "string" } }], responses: { "200": { description: "Published agent action catalog" }, "400": { description: "workspaceSlug missing for the service bearer" }, "401": { description: "Session or bearer required" }, "403": { description: "workspaceSlug belongs to a different organization" } } } },
      "/api/marketplace/broker/grants": { post: { security: bearerSecurity, tags: ["Execution"], summary: "Issue a single-use scoped Composio broker grant", description: "Internal services only. Grants are stored as token hashes, expire within at most 900 seconds, and are consumed atomically before provider dispatch.", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["requesterMiniappId", "pluginId", "actionKeys"], properties: { requesterMiniappId: { type: "string" }, pluginId: { type: "string" }, actionKeys: { type: "array", minItems: 1, items: { type: "string" } }, ttlSeconds: { type: "integer", minimum: 1, maximum: 900, default: 300 } } } } } }, responses: { "201": { description: "Single-use grant issued" }, "400": { description: "Invalid scope or TTL" }, "401": { description: "Unauthorized" }, "403": { description: "Rules denied" } } } },
      "/api/marketplace/hub/records": { get: { security: bearerSecurity, tags: ["Hub service"], summary: "Project normalized records to the HDDA Host SDK", responses: { "200": { description: "Projection" }, "401": { description: "Unauthorized" }, "503": { description: "Service auth unconfigured" } } } },
      "/api/marketplace/hub/plugins/{pluginId}/lifecycle": { post: { security: bearerSecurity, tags: ["Hub service"], summary: "Internal Host SDK lifecycle including enable, disable, and reload", parameters: [{ name: "pluginId", in: "path", required: true, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "200": { description: "Lifecycle changed" }, "401": { description: "Unauthorized" } } } },
      "/api/marketplace/v1/broker/composio/execute": { post: { security: bearerSecurity, tags: ["Execution"], summary: "Authenticated cross-app Composio broker execution", description: "Issues and consumes one internal single-use grant for this call; raw provider credentials are never returned.", requestBody: { required: true, content: { "application/json": { schema: jsonObject } } }, responses: { "200": { description: "Executed" }, "401": { description: "Unauthorized" }, "403": { description: "Rules denied" } } } },
    },
    "x-doppelganger-commands": [
      { id: "list-cards", method: "GET", path: "/api/marketplace/cards/summary?workspaceSlug={workspaceSlug}&limit=60" },
      { id: "read-card", method: "GET", path: "/api/marketplace/cards/{pluginId}?workspaceSlug={workspaceSlug}" },
      { id: "install", method: "POST", path: "/api/marketplace/plugins/{pluginId}/install" },
      { id: "connect", method: "POST", path: "/api/marketplace/plugins/{pluginId}/connection" },
      { id: "bind-action", method: "POST", path: "/api/marketplace/plugins/{pluginId}/action-binding" },
      { id: "inspect-audit", method: "GET", path: "/api/marketplace/audit?workspaceSlug={workspaceSlug}" },
    ],
    "x-doppelganger-templates": {
      install: { workspaceSlug: "default", actorId: "operator" },
      connectComposio: { workspaceSlug: "default", actorId: "operator", provider: "github", backend: "composio" },
      bindAction: { workspaceSlug: "default", actorId: "operator", actionKey: "github.tool.execute", enabled: true },
      execute: { workspaceSlug: "default", actorId: "operator", capability: "connector.dispatch", action: { type: "github.tool.execute" } },
    },
  };
}
